version: '3'
services:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: .
        environment: 
            - NODE_ENV=development
        ports:
            - '8080:8080'
